kind: pipeline
type: docker
name: git_project_status

steps:
- name: pylint
  image: python:3.8
  pull: always
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  # W0511 = TODO
  - pipenv run pylint --disable=W0511 git_project_status.py
- name: pytest
  image: python:3.8
  pull: always
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pytest
